### Create A Report

POST http://localhost:3000/reports
Content-Type: application/json

{
    "make":"BYD",
    "model":"Elec",
    "year":2025,
    "mileage":100,
    "lng":0,
    "lat":0,
    "price":10000
}

### Approve existing report
PATCH  http://localhost:3000/reports/6
Content-Type:application/json

{
    "approved": false
}