### Create A Report

POST http://localhost:3000/reports
Content-Type: application/json

{
    "make":"Honda",
    "model":"Just",
    "year":2002,
    "mileage":200,
    "lng":0,
    "lat":0,
    "price":1000
}