
### Create New User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"user2@user.com",
    "password":"user123"
}

### Singin user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email":"user2@user.com",
    "password":"user123"
}

### find a user by Id
GET http://localhost:3000/auth/2

### Find all users
GET http://localhost:3000/auth?email=sara@roshan.com

### Delete user by id
DELETE  http://localhost:3000/auth/1

### Update Uder by id
PATCH  http://localhost:3000/auth/3
Content-Type: application/json

{
    "password":"test1234"
}

